# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20ba32527e2b3c9df710d724fdfda0907e0e91abcfaf10ee90e52b5f8da83298ffa294fb6d8707472cbe7a369d3bde77ab0632904d600a063a7e1e3c0d993749

test:
  secret_key_base: 6cb0155470c6398e3b5aa46bc45adf3f12aaaf8af9137c82f88a661f713c65285ac3ef042fffc5492adea748458f29c87fa3cb0873fa472503eef7fa26aff995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
